### ISSUE TITLE
i can't found result file after unpack

### ISSUE THREAD

**Issue by mostafakamelomarrslan** [TheHellTower/pycdc#4]
after make exe and use it i can't found result file

**Comment by TheHellTower** [comment]
> after make exe and use it i can't found result file

Could you verify the command you type ?

The command should looks like this: 
`pycdc.exe <script>.pyc > <script>.py`

**Comment by TheHellTower** [comment]
> not work Error opening file mai1.py Could not load file mai1.py

Please record your screen while you do it because I'm pretty sure you are not in the good path with the shell, the tool is made for pyc(compiled python script) not for py(python script)

**Comment by mostafakamelomarrslan** [comment]
oh thanks it's worked now =>pycdc.exe example.pyc > output.py

there is some codes not unpacked success

**Comment by TheHellTower** [comment]
> oh thanks it's worked now =>pycdc.exe example.pyc > output.py
> 
> there is some codes not unpacked success

Perfect this issue is solved ! Now [open a issue based on this one](https://github.com/TheHellTower/pycdc/issues/new?title=Add%20support%20for%20%3Cunsupported%20opcode%3E&body=File%20for%20tests:%20%3Cdownload%20link%3E) thanks ! if it's related to a opcode or just open a new normal issue if it doesn't relate to a opcode
